title: Heatmint Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.heatmint.com/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Alive
      category: Physical Health
    - name: Hungry?
      category: Physical Health
    - name: Thirsty?
      category: Physical Health
    - name: Happy?
      category: Mental Health
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo-removebg-preview.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Physical Health
    - name: Mental Health
    - name: Other
  description: Is Heatmint still Alive?
  enableCustomHTML: true
  useLargeHeaderDesign: false
